apiVersion: v1
kind: Service
metadata:
  name: {{.Values.application.name}}
  labels:
    run: {{.Values.application.name}}
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: devops-arkon
  type: LoadBalancer
